// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3bwjJ4D7xmc2jHpA8AW2TrwGIT4zoQIk',
    appId: '1:723426063324:web:67ddca7affa22e0a79d519',
    messagingSenderId: '723426063324',
    projectId: 'tiktok-tutorial-d3d42',
    authDomain: 'tiktok-tutorial-d3d42.firebaseapp.com',
    storageBucket: 'tiktok-tutorial-d3d42.appspot.com',
    measurementId: 'G-JBTH41N47J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXJqHfRm6_ptYmmmn4I2chRXrlXvVWwA',
    appId: '1:723426063324:android:9984fbe83b47e7f079d519',
    messagingSenderId: '723426063324',
    projectId: 'tiktok-tutorial-d3d42',
    storageBucket: 'tiktok-tutorial-d3d42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBexyzJqP53hjdjb8ztYFIxZyRzzFUSQgY',
    appId: '1:723426063324:ios:e2a13d4b1458b1b279d519',
    messagingSenderId: '723426063324',
    projectId: 'tiktok-tutorial-d3d42',
    storageBucket: 'tiktok-tutorial-d3d42.appspot.com',
    iosBundleId: 'com.kazungudev.tiktokTutorial',
  );
}
